### ISSUE TITLE
Notebook: Add object storage (or wget)

### ISSUE THREAD

**Issue by scottdangelo** [IBM/customer-churn-prediction#5]
We need to provide code and Readme instructions for getting and loading the data set.
The best method is to download the data locally from the web link.
Then, use watson studio to load  the data (see [this pattern step 3](https://github.com/IBM/predictive-model-on-watson-ml#3-create-a-project-in-ibm-watson-studio-and-bind-it-to-your-watson-machine-learning-service-instance) under the bullet point `From within the new project Overview panel, click Add to project on the top right, selecting Data asset.` for an example)

Then, we need to show how to import the data into the notebook. [Here is an example using Spark data frames](https://github.com/IBM/predictive-model-on-watson-ml#6-run-the-notebook-in-ibm-watson-studio).

**Comment by HebaNAS** [comment]
I will write detailed instructions for importing the dataset to Watson Studio in the Readme. As for the notebook, currently the cells containing credentials are hidden, should I keep it as is and explain in the Readme, or show the whole code in the notebook as well?

**Comment by HebaNAS** [comment]
I can also add the wget script to download the dataset from the notebook as another alternative/quick option:

`!wget https://community.watsonanalytics.com/wp-content/uploads/2015/03/WAFn-UseC-Telco-Customer-Churn.csv --output-document=dataset/telco-customer-churn.csv`
